### ISSUE TITLE
[BE] Add multilanguage support

### ISSUE THREAD

**Issue by CloudSalander** [IT-Academy-BCN/ita-profiles-backend#18]

**Comment by CloudSalander** [comment]
Pending to know if we need Translatable.

**Comment by FranEnLaNube** [comment]
I've moved this task back to the 'Backlog' because, while it's true that Laravel Lang has been implemented as stated in #23, we still need to make a decision regarding translatable support, as mentioned in that PR under item C and in the latest Ruben's comment in this Issue. 
There is a lengthy workflow related to this subject in our other project, with the most recent PR being https://github.com/IT-Academy-BCN/ita-landing-backend/pull/110
